apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: elastic6
    meta.helm.sh/release-namespace: graylog
  creationTimestamp: "2021-10-14T02:42:44Z"
  labels:
    app: elasticsearch
    app.kubernetes.io/managed-by: Helm
    chart: elasticsearch-1.32.2
    component: client
    heritage: Helm
    release: elastic6
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:chart: {}
          f:component: {}
          f:heritage: {}
          f:release: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":9200,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
          f:component: {}
          f:release: {}
        f:sessionAffinity: {}
    manager: Go-http-client
    operation: Update
    time: "2021-10-20T04:57:21Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          k:{"port":9200,"protocol":"TCP"}:
            f:nodePort: {}
        f:type: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-10-20T05:24:20Z"
  name: elastic6-elasticsearch-client
  namespace: graylog
  resourceVersion: "25759850"
  selfLink: /api/v1/namespaces/graylog/services/elastic6-elasticsearch-client
  uid: 306e27ff-b580-4753-993d-aebf3e44e97d
spec:
  clusterIP: 10.233.45.117
  clusterIPs:
  - 10.233.45.117
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 31597
    port: 9200
    protocol: TCP
    targetPort: http
  selector:
    app: elasticsearch
    component: client
    release: elastic6
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
