apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["100.65.16.10"],"port":30829,"protocol":"TCP","serviceName":"graylog:gelf-http","allNodes":true}]'
    meta.helm.sh/release-name: graylog
    meta.helm.sh/release-namespace: graylog
  creationTimestamp: "2021-10-13T06:32:04Z"
  labels:
    app.kubernetes.io/component: TCP
    app.kubernetes.io/instance: graylog
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: graylog
    app.kubernetes.io/version: 4.1.3
    helm.sh/chart: graylog-1.8.9
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":12201,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/name: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: Go-http-client
    operation: Update
    time: "2021-10-13T06:32:04Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:field.cattle.io/publicEndpoints: {}
    manager: rancher
    operation: Update
    time: "2021-10-13T07:48:26Z"
  name: gelf-http
  namespace: graylog
  resourceVersion: "24642351"
  selfLink: /api/v1/namespaces/graylog/services/gelf-http
  uid: 9934ebb3-cc82-4985-b6bd-f8817d5c7a71
spec:
  clusterIP: 10.233.50.37
  clusterIPs:
  - 10.233.50.37
  externalTrafficPolicy: Cluster
  ports:
  - name: gelf
    nodePort: 30829
    port: 12201
    protocol: TCP
    targetPort: 12201
  selector:
    app.kubernetes.io/instance: graylog
    app.kubernetes.io/name: graylog
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
