apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["100.65.16.10"],"port":32230,"protocol":"TCP","serviceName":"graylog:graylog-web","allNodes":true}]'
    meta.helm.sh/release-name: graylog
    meta.helm.sh/release-namespace: graylog
  creationTimestamp: "2021-10-13T06:32:04Z"
  labels:
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: graylog
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: graylog
    app.kubernetes.io/version: 4.1.3
    helm.sh/chart: graylog-1.8.9
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":9000,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/name: {}
        f:sessionAffinity: {}
    manager: Go-http-client
    operation: Update
    time: "2021-10-13T06:32:04Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:externalTrafficPolicy: {}
        f:type: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-10-13T06:36:21Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:field.cattle.io/publicEndpoints: {}
    manager: rancher
    operation: Update
    time: "2021-10-13T07:48:26Z"
  name: graylog-web
  namespace: graylog
  resourceVersion: "19243359"
  selfLink: /api/v1/namespaces/graylog/services/graylog-web
  uid: 033f6805-83e7-4f2b-8955-aaa2627122a3
spec:
  clusterIP: 10.233.48.254
  clusterIPs:
  - 10.233.48.254
  externalTrafficPolicy: Cluster
  ports:
  - name: graylog
    nodePort: 32230
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app.kubernetes.io/instance: graylog
    app.kubernetes.io/name: graylog
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
